[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  # Увеличиваем лимит памяти для Node.js
  NODE_OPTIONS = "--max_old_space_size=4096"

# Перенаправления для SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Заголовки для безопасности и кэширования
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 